/* Generated by Cython 3.0.10 */

#ifndef __PYX_HAVE_API__joe__model__astro__ellip_hack
#define __PYX_HAVE_API__joe__model__astro__ellip_hack
#ifdef __MINGW64__
#define MS_WIN64
#endif
#include "Python.h"

static double (*__pyx_api_f_3joe_5model_5astro_10ellip_hack_c_ellipe)(double) = 0;
#define c_ellipe __pyx_api_f_3joe_5model_5astro_10ellip_hack_c_ellipe
static double (*__pyx_api_f_3joe_5model_5astro_10ellip_hack_c_ellipk)(double) = 0;
#define c_ellipk __pyx_api_f_3joe_5model_5astro_10ellip_hack_c_ellipk
#ifndef __PYX_HAVE_RT_ImportFunction_3_0_10
#define __PYX_HAVE_RT_ImportFunction_3_0_10
static int __Pyx_ImportFunction_3_0_10(PyObject *module, const char *funcname, void (**f)(void), const char *sig) {
    PyObject *d = 0;
    PyObject *cobj = 0;
    union {
        void (*fp)(void);
        void *p;
    } tmp;
    d = PyObject_GetAttrString(module, (char *)"__pyx_capi__");
    if (!d)
        goto bad;
    cobj = PyDict_GetItemString(d, funcname);
    if (!cobj) {
        PyErr_Format(PyExc_ImportError,
            "%.200s does not export expected C function %.200s",
                PyModule_GetName(module), funcname);
        goto bad;
    }
    if (!PyCapsule_IsValid(cobj, sig)) {
        PyErr_Format(PyExc_TypeError,
            "C function %.200s.%.200s has wrong signature (expected %.500s, got %.500s)",
             PyModule_GetName(module), funcname, sig, PyCapsule_GetName(cobj));
        goto bad;
    }
    tmp.p = PyCapsule_GetPointer(cobj, sig);
    *f = tmp.fp;
    if (!(*f))
        goto bad;
    Py_DECREF(d);
    return 0;
bad:
    Py_XDECREF(d);
    return -1;
}
#endif


static int import_joe__model__astro__ellip_hack(void) {
  PyObject *module = 0;
  module = PyImport_ImportModule("joe.model.astro.ellip_hack");
  if (!module) goto bad;
  if (__Pyx_ImportFunction_3_0_10(module, "c_ellipe", (void (**)(void))&__pyx_api_f_3joe_5model_5astro_10ellip_hack_c_ellipe, "double (double)") < 0) goto bad;
  if (__Pyx_ImportFunction_3_0_10(module, "c_ellipk", (void (**)(void))&__pyx_api_f_3joe_5model_5astro_10ellip_hack_c_ellipk, "double (double)") < 0) goto bad;
  Py_DECREF(module); module = 0;
  return 0;
  bad:
  Py_XDECREF(module);
  return -1;
}

#endif /* !__PYX_HAVE_API__joe__model__astro__ellip_hack */
